### ISSUE TITLE
win7和electron 1.6.6下报错了

### ISSUE THREAD

**Issue by amhoho** [hankbao/electron-notify#14]
win7和electron 1.6.6下报错了

C:\Users\Administrator\Desktop\demo\electron-notify-0.1.0>electron .

App threw an error during load
Error: Cannot require "screen" module before app is ready
    at process.atomBinding (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\electron\dist\resources\electron.asar\common\atom-binding-setup.js:7:16)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\electron\dist\resources\electron.asar\browser\api\screen.js:2:34)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\electron\dist\resources\electron.asar\browser\api\screen.js:8:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by hankbao** [comment]
Error: Cannot require "screen" module before app is ready

需要在 screen 模块加载后加载

**Comment by gordomium** [comment]
😏
