### ISSUE TITLE
Error: Object has been destroyed

### ISSUE THREAD

**Issue by ravisojitra** [hankbao/electron-notify#23]
**Error & Stack Trace**
Error: Object has been destroyed
    at D:\ionic\demos\electron\HK-hardika\myapp-source\node_modules\electron-notify\index.js:309:23
    at AnimationQueue.animate (D:\ionic\demos\electron\HK-hardika\myapp-source\node_modules\electron-notify\index.js:28:15)
    at D:\ionic\demos\electron\HK-hardika\myapp-source\node_modules\electron-notify\index.js:32:20
    at <anonymous>

**Code:**

```
function A(){
     eNotify.closeAll();
  eNotify.setConfig({
    animateInParallel: true,
    appIcon : path.join(__dirname, "./logo.ico")
  });

  eNotify.notify({ 
    title: 'Your offline data are being synced to online', 
    text: 'Please wait a while' 
  });
  setTimeout(function(){
    otherFunction();
  })
}

otherFunction(){
   eNotify.closeAll();
  
  eNotify.setConfig({
    animateInParallel: true,
    appIcon : path.join(__dirname, "./logo.ico")
  });

  eNotify.notify({ 
    title: 'Your offline data are synced successfully', 
    text: 'Please wait while we redirect you',
    displayTime: 5000 
  });
}
```

**Comment by mashahbazi** [comment]
I have same issue and my solution for this is changing some part of codes. this happen when you destroy the electron window but notification want too use it so I go to index.js and change method `getWindow()` like this:
```
function getWindow() {
    return new Promise(function (resolve) {
        let notificationWindow
        // Are there still inactiveWindows?
        if (inactiveWindows.length > 0) {
            notificationWindow = inactiveWindows.pop()
            try {
                notificationWindow.setPosition(0,0,false)
                resolve(notificationWindow)
            }catch (e) {
                let windowProperties = config.defaultWindow
                windowProperties.width = config.width
                windowProperties.height = config.height
                notificationWindow = new BrowserWindow(windowProperties)
                notificationWindow.setVisibleOnAllWorkspaces(true)
                notificationWindow.loadURL(getTemplatePath())
                notificationWindow.webContents.on('did-finish-load', function () {
                    // Done
                    notificationWindow.webContents.send('electron-notify-load-config', config)
                    resolve(notificationWindow)
                })
            }
        } else { // Or create a new window
            let windowProperties = config.defaultWindow
            windowProperties.width = config.width
            windowProperties.height = config.height
            notificationWindow = new BrowserWindow(windowProperties)
            notificationWindow.setVisibleOnAllWorkspaces(true)
            notificationWindow.loadURL(getTemplatePath())
            notificationWindow.webContents.on('did-finish-load', function () {
                // Done
                notificationWindow.webContents.send('electron-notify-load-config', config)
                resolve(notificationWindow)
            })
        }
    })
}
```
at this code notification try to setPosition and if it throw error catch and create window from start
