### ISSUE TITLE
Exception on shutdown

### ISSUE THREAD

**Issue by sashazxtt** [hankbao/electron-notify#9]
It appears that there is a problem that exists on the shutdown.
If Electron is shut down while notifications exist, I get this error below.

Looks like the async animation is not terminated properly on the app shutdown.

main error= Error: Object has been destroyed
    at Error (native)
    at Timeout._repeat (...\node_modules\electron-notify\index.js:424:24)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

**Comment by hankbao** [comment]
Thanks for reporting this issue. Recently I've been working on some other projects. So the problem may take some time to be fixed.

BTW, any pull request is welcomed.
